name: Flutter APK Auto Release

on:
  push:
    tags:
      - 'v*' # Solo se activa cuando haces git push con un tag como v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar dependencias
        run: flutter pub get

      - name: Decodificar keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/app/zeroweather-release-key.jks

      - name: Crear key.properties
        run: |
          cat > android/key.properties <<EOF
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          storeFile=zeroweather-release-key.jks
          EOF

      - name: Compilar APK firmado
        run: flutter build apk --release

      - name: Crear Release en GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
